id: queen-server-id
subscription_quota_enabled: false
jobs:
  launch_topic_suffix: -anon-local
db:
  db_type: sqlite
  data_source: .formicary_db.sqlite
  encryption_key: my-db-key
  _db_type: mysql
  _data_source: formicary_user_dev:formicary_pass@tcp(localhost:3306)/formicary_dev?charset=utf8mb4&parseTime=true&loc=Local
common:
  development: true
  user_agent: ""
  proxy_url: ""
  public_dir: "./public/"
  messaging_provider: REDIS_MESSAGING
  http_port: 0
  external_base_url: http://localhost:7777
  xmonitoring_urls:
    docker: "localhost:2375"
  disabled_pulsar:
    url: "pulsar://localhost:6650"
    connection_timeout: 30
  redis:
    host: "192.168.1.102"
    port: 6379
  s3:
    endpoint: "192.168.1.102:9000"
    accessKeyID: "admin"
    secretAccessKey: "password"
    region: "us-west-2"
    bucket: "formicary-artifacts"
    prefix: "formicary/"
  auth:
    enabled: false
    jwt_secret: changeme
smtp:
    from_email: "support@formicary.io"
    provider: ""
    api_key: ""
    username: ""
    password: ""
    host: ""
    port: 0
notify:
    email_jobs_template_file: views/notify/email_notify_job.html
    slack_jobs_template_file: views/notify/slack_notify_job.txt
    verify_email_template_file: views/notify/verify_email.html
    user_invitation_template_file: views/notify/user_invitation.html
