version: '3.7'
services:
  pulsar:
    image: apachepulsar/pulsar:2.8.1
    ports:
      - "6650:6650" # Pulsar broker port
      - "8080:8080" # Pulsar admin port
    volumes:
      - pulsar-data:/pulsar/data
      - pulsar-conf:/pulsar/conf
  minio:
    image: minio/minio:RELEASE.2024-02-09T21-25-16Z
    volumes:
      - minio-data1-1:/data1
      - minio-data1-2:/data2
    expose:
      - "9000"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    command: server http://minio{1...2}/data{1...2}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
  postgres:
    image: "postgres:14.11-bullseye"
    ports:
      - "5432:5432"
    environment:
      DB_NAME: ${DB_NAME:-formicary_db}
      POSTGRES_USER: ${DB_USER:-formicary_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-formicary_pass}
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres-data:/var/lib/postgresql/data
  formicary-server:
    image: plexobject/formicary
#    build:
#      context: .
#      dockerfile: Dockerfile
    depends_on:
      - pulsar
      - postgres
      - minio
    environment:
      COMMON_PULSAR_URL: 'pulsar://pulsar:6650'
      COMMON_S3_ENDPOINT: 'minio:9000'
      COMMON_AWS_ACCESS_KEY_ID: '${AWS_ACCESS_KEY_ID:-admin}'
      COMMON_AWS_SECRET_ACCESS_KEY: '${AWS_SECRET_ACCESS_KEY:-password}'
      COMMON_AWS_DEFAULT_REGION: '${AWS_DEFAULT_REGION:-us-west-2}'
      COMMON_BUCKET: '${BUCKET:-formicary-artifacts}'
      COMMON_PREFIX: '${PREFIX:-formicary}'
      CONFIG_FILE: ${CONFIG_FILE:-/config/formicary-queen.yaml}
      HTTP_PORT: ${HTTP_PORT:-7777}
      DB_HOST: 'mysql'
      DB_TYPE: "mysql"
      DB_SOURCE: "mysql://$DB_USER:$DB_PASSWORD@tcp($DB_HOST:$DB_PORT)/$DB_NAME?parseTime=true" 
    ports:
      - 7777:7777
    volumes:
      - ./config:/config
      - ./formicary-queen.yaml:/config/formicary-queen.yaml
    entrypoint: ["sh", "-c", "/migrations/setup_db.sh && exec /formicary --config=formicary-queen.yaml --id=formicary-server-id1 --port $HTTP_PORT"]
volumes:
  minio-data1-1:
  minio-data1-2:
  pulsar-data:
  pulsar-conf:
  postgres-data:
